---
kind: Service
apiVersion: v1
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
  - port: 8091
    targetPort: http-server
  selector:
    app: demo
  type: LoadBalancer

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ec2-63-34-137-130.eu-west-1.compute.amazonaws.com:8083/spring-boot-rest-example:27
        ports:
        - name: http-server
          containerPort: 8091
      imagePullSecrets:
        - name: regcred

